### ISSUE TITLE
D7 upgrade results in Notice: Undefined offset: 1 in captcha_get_form_id_setting()

### ISSUE THREAD

**Issue by bugfolder** [backdrop-contrib/captcha#11]
After upgrading a site from D7, there are many watchdog entries of the form

```
Notice: Undefined offset: 1 in captcha_get_form_id_setting() (line 100 of /mysite/modules/contrib/captcha/captcha.inc).
```

The root cause of these reports is because in the update hook `captcha_update_1000()`, the variable `captcha_default_challenge` is converted to a config variable of the same name. But in every other case, the variable prefix `captcha_` is removed during the conversion to config, so by rights, variable `captcha_default_challenge` should have been converted to config variable `default_challenge`.

And indeed, there are many references to the latter in the module; in particular, the line in `captcha_get_form_id_setting()` that causes this error:

```
      list($module, $type) = explode('/', config_get('captcha.settings', 'default_challenge'));
```

The error is generated because there is no config setting of `default_challenge`. There is, instead, a config setting of `captcha_default_challenge` that never gets used.

The solution is straightforward, I think: add another update hook that converts the config variable `captcha_default_challenge` to `default_challenge`if it isn't already converted or set by the site admin.

PR to follow.

**Comment by herbdool** [comment]
Thanks @bugfolder !
