### ISSUE TITLE
`The website encountered an unexpected error. Please try again later.` on the config page

### ISSUE THREAD

**Issue by shrop** [backdrop-contrib/captcha#2]
I enabled captcha and I get an error message on the config page at `/admin/config/people/captcha`.

The error is `The website encountered an unexpected error. Please try again later.`

I am checking to see what the php error is in the server logs. Will report back.

**Comment by herbdool** [comment]
@shrop I'm unable to replicate your error after completely uninstalling/reinstalling captcha. If you get more info please let me know.

**Comment by shrop** [comment]
A bit more info. Getting the following error referenced by this page: `/admin/config/people/captcha`.

Recoverable fatal error: Argument 1 passed to backdrop_sort() must be of the type array, null given, called in /home/hb5.co/public_html/modules/captcha/captcha.inc on line 134 and defined in backdrop_sort() (line 6640 of /home/hb5.co/public_html/core/includes/common.inc).

Thanks!

**Comment by herbdool** [comment]
right. I've created a new minor release: https://github.com/backdrop-contrib/captcha/tree/1.x-1.3.1 which hopefully fixes it for you. backdrop_sort() is expecting an array of captcha points so I've added an empty array so it doesn't throw an error or on a fresh install there will be a default captcha point on the registration form.
