### ISSUE TITLE
Error message when I am in the Settings Captcha

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/captcha#4]
Hello Webdeveloper,

I use Backdrop 1.2 and when I run it in the browser URL (/admin/config/people/captcha/captcha/settings), I see this error message. 

```
Warning: htmlspecialchars () Expects parameter 1 to be string, object Given in check_plain () (line 1848 of /www/htdocs/xxxxxxxxxxx/cms/backdrop/core/includes/bootstrap.inc).
```

How can you eliminate? Thank you in advance.

**Comment by herbdool** [comment]
I'll look into it. Thanks for reporting it.

**Comment by herbdool** [comment]
I'm unable to replicate your issue. I installed CAPTCHA on a fresh Backdrop 1.2.1 site and went to the settings page. I tried a bunch of different settings and didn't see your error. It seems that this might be the result of a different module.

**Comment by ghost** [comment]
Ok, thanks for the answer. I'll be watching the matter and if there still get errors, then you can see. Maybe it was even temporarily.
