### ISSUE TITLE
backdrop_sort fatal error when going to the settings page

### ISSUE THREAD

**Issue by herbdool** [backdrop-contrib/captcha#5]
When migrating a site to Backdrop that was upgraded from Drupal 6 to 7 and had captcha previously, I get this error on the settings page:

`Catchable fatal error: Argument 1 passed to backdrop_sort() must be of the type array, null given, called in /home/backdrop/modules/contrib/captcha/captcha.inc on line 134 and defined in /home/backdrop/core/includes/common.inc on line 6812`

**Comment by Graytone** [comment]
Доброго времени суток.
 В бэкдропе при переходе в настойки модуля captcha  сервер отдает ошибку 500
 Лог пишет
 PHP Fatal error:  Call to undefined function locale_language_list() in /home/username/domains/mihail.space/modules/captcha/captcha.admin.inc on line 159
 
 Если на  время модуль locale выключить, то к настройкам можно пройти.
