### ISSUE TITLE
 PHP Fatal error:  Call to undefined function locale_language_list() in 

### ISSUE THREAD

**Issue by ghost** [backdrop-contrib/captcha#6]
Good day
 /admin/config/people/captcha
 PHP Fatal error:  Call to undefined function locale_language_list() in /home/username/domains/mihail.space/modules/captcha/captcha.admin.inc on line 159

 If at the time disable  module locale, then path is working

**Comment by herbdool** [comment]
Make sure you're using the latest release: https://github.com/backdrop-contrib/captcha/archive/1.x-1.3.2.zip since that was already fixed in the module. Let me know if you've still got problems.

**Comment by ghost** [comment]
https://github.com/backdrop-contrib/captcha/archive/1.x-1.3.2.zip
without changes

**Comment by herbdool** [comment]
My mistake. I hadn't made a new release after the last fix. This should be better: https://github.com/backdrop-contrib/captcha/archive/1.x-1.3.3.zip
