### ISSUE TITLE
Notice: Undefined offset: 1 in captcha_get_form_id_setting

### ISSUE THREAD

**Issue by laryn** [backdrop-contrib/captcha#9]
On an upgraded D7 site, I get this on the login screen:

> Notice: Undefined offset: 1 in captcha_get_form_id_setting() (line 99 of /path/modules/captcha/captcha.inc).

When I go to the configuration page for Captcha, it looks like some of the settings from the D7 site were not transferred over (including default challenge type, form IDs, Captcha description). After I re-enter and save config, the notice no longer shows up.

**Comment by herbdool** [comment]
I haven't seen the specific error with a d7 upgrade but I did notice that I hadn't migrated captcha_points from the table. Maybe I just didn't feel like it a few years ago? Anyway, it's there now https://github.com/backdrop-contrib/captcha/commit/6c2ae1d69d4cbf526798c30b2ab1afe1c476cc76. It'll only run if it's empty and/or set to the default still.

**Comment by nattywebdev** [comment]
Just seen this error too, on a site I've fully upgraded. Is there a way I can apply this change to the db directly without having to re-start my upgrade from scratch?
